disabled_rules:
- trailing_whitespace
- type_name

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

function_body_length:
- 99 # warning
- 100 #error

file_length:
- 999 # warning
- 1000 # error

type_body_length:
- 99 # warning
- 100 # error

line_length:
- 219 # warning
- 220 # error

cyclomatic_complexity:
- 9 # warning
- 10 # error

excluded:
- Carthage
